[package]
name = "postgres-flatten-impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
postgres = "0.19"
itertools = "0.10.5"

[dependencies.syn]
version = "2.0"
features = ["extra-traits"]
